services:

  client:
    container_name: test-clien-dev
    image: test/clien-dev
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      target: dev
    ports:
      - "3000:3000" # Проброс порта для среды разработки
    environment:
      NODE_ENV: dev
      AUTH_SERVICE_URL: http://server:3010
    volumes:
      - ./client:/app
      - /app/node_modules # это для того, чтобы node_modules не удалялись в контейнере
    networks:
      - dev-network
    command: ["npm", "start"]

  server:
    container_name: test-server-dev
    image: test/server-dev
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: dev
    ports:
      - "3010:3010" # Проброс порта для среды разработки
    environment:
      NODE_ENV: dev
    volumes:
      - ./server:/app
      - /app/node_modules # это для того, чтобы node_modules не удалялись в контейнере
    networks:
      - dev-network
    command: ["npm", "run", "dev"]
  

volumes:
  test-data:
    driver: local
    
networks:
  dev-network:
    driver: bridge